branches:
  - main

plugins:
  # Uses the RELEASE_TYPE env var (major | minor | patch) instead of analyzing commits
  - - "@semantic-release/exec"
    - analyzeCommitsCmd: "if [ ${commits.length} -eq 0 ]; then exit 0; else printf '<%= process.env.RELEASE_TYPE %>'; fi"
      success: "echo VERSION=<%= nextRelease.gitTag %> > version.env"
