apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: cert-issuer
deploy:
  helm:
    releases:
      - name: cert-issuer
        chartPath: deployment/helm/cert-issuer
        namespace: "{{ .NAMESPACE }}"
        createNamespace: true
        wait: true
        setValueTemplates:
          environment: "{{ .DEPLOYMENT_ENV }}"
          email: "{{ .DOMAIN_ADMIN_EMAIL }}"
        valuesFiles:
          - deployment/helm/cert-issuer/values.yaml

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: gateway
deploy:
  helm:
    releases:
      - name: "{{ .NAMESPACE }}-namespace-gateway"
        chartPath: deployment/helm/gateway
        namespace: "{{ .NAMESPACE }}"
        createNamespace: true
        wait: true
        valuesFiles:
          - deployment/helm/gateway/values.yaml
        setValues:
          nameOverride: gateway # should match the routes below
        setValueTemplates:
          environment: "{{ .DEPLOYMENT_ENV }}"
          cert.environment: "{{ .DEPLOYMENT_ENV }}"
          hostnames:
            tld: "{{ .DOMAIN_NAME }}"
            auth: "auth.{{ .DOMAIN_NAME }}"
---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: frontend
build:
  artifacts:
    - image: frontend
      context: .
      docker:
        dockerfile: frontend/Dockerfile
        target: dev
      sync:
        manual:
          - src: "frontend/src/**/*"
            dest: /app
  tagPolicy:
    envTemplate:
      template: "{{ or .VERSION .NAMESPACE }}"
  local:
    push: true
deploy:
  helm:
    releases:
      - name: frontend
        chartPath: deployment/helm/frontend
        namespace: "{{ or .NAMESPACE default }}"
        createNamespace: true
        setValues:
          nameOverride: frontend
          image.ports.containerPort: 5173
        setValueTemplates:
          image.repository: "{{ .IMAGE_REPO_frontend }}"
          image.tag: "{{ .IMAGE_TAG_frontend }}@{{ .IMAGE_DIGEST_frontend }}"
profiles:
  - name: prod
    patches:
      - op: replace
        path: /build/artifacts/0/docker/target
        value: prod
      - op: replace
        path: /deploy/helm/releases/0/setValues/image.ports.containerPort
        value: 80
  - name: staging
    patches:
      - op: replace
        path: /build/artifacts/0/docker/target
        value: staging
      - op: replace
        path: /deploy/helm/releases/0/setValues/image.ports.containerPort
        value: 80
  - name: dev

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: backend
build:
  artifacts:
    - image: backend
      context: .
      docker:
        dockerfile: backend/Dockerfile
        target: dev
      sync:
        manual:
          - src: "backend/src/**/*"
            dest: /app
  tagPolicy:
    envTemplate:
      template: "{{ or .VERSION .NAMESPACE }}"
  local:
    push: true
deploy:
  helm:
    releases:
      - name: backend
        chartPath: deployment/helm/backend
        namespace: "{{ or .NAMESPACE default }}"
        createNamespace: true
        setValues:
          nameOverride: backend
          image.ports.containerPort: 5000
        setValueTemplates:
          image.repository: "{{ .IMAGE_REPO_backend }}"
          image.tag: "{{ .IMAGE_TAG_backend }}@{{ .IMAGE_DIGEST_backend }}"
profiles:
  - name: prod
    patches:
      - op: replace
        path: /build/artifacts/0/docker/target
        value: prod
  - name: staging
    patches:
      - op: replace
        path: /build/artifacts/0/docker/target
        value: staging
  - name: dev

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: documentation
build:
  artifacts:
    - image: thing_control_panel_docs
      context: .
      docker:
        dockerfile: documentation/Dockerfile
        target: dev
      # mkdocs reloading not working
      sync:
        manual:
          - src: "documentation/docs/**/*"
            dest: "/app"
          - src: "documentation/mkdocs.yml"
            dest: "/app"
          - src: "documentation/main.py"
            dest: "/app"
  tagPolicy:
    envTemplate:
      template: dev
  local:
    push: true
deploy:
  helm:
    releases:
      - name: documentation
        chartPath: deployment/helm/documentation
        namespace: "{{ or .NAMESPACE default }}"
        createNamespace: true
        setValues:
          nameOverride: documentation
          image.ports.containerPort: 8000
        setValueTemplates:
          image:
            repository: "{{ .IMAGE_REPO_thing_control_panel_docs }}"
            tag: "{{ .IMAGE_TAG_thing_control_panel_docs }}@{{ .IMAGE_DIGEST_thing_control_panel_docs }}"
profiles:
  - name: prod
    patches:
      - op: replace
        path: /build/artifacts/0/docker/target
        value: prod
  - name: staging
    patches:
      - op: replace
        path: /build/artifacts/0/docker/target
        value: staging
  - name: dev

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: zitadel-iam
deploy:
  helm:
    releases:
      - name: zitadel-iam
        chartPath: deployment/helm/zitadel
        namespace: "{{ .NAMESPACE }}"
        createNamespace: true
        wait: true
        valuesFiles:
          - deployment/helm/zitadel/values-override.yaml
        setValueTemplates:
          zitadel.zitadel.configmapConfig.ExternalDomain: "auth.{{ .DOMAIN_NAME }}"
          zitadel.zitadel.configmapConfig.FirstInstance.Org.Human.Email: "{{ .DOMAIN_ADMIN_EMAIL }}"
          zitadel.zitadel.configmapConfig.FirstInstance.Org.Human.Password: "{{ .IAM_ADMIN_PASSWORD }}"