nameOverride: ""
fullnameOverride: ""

enabled: true
environment: dev
component: gateway

externalDNS: true

hostnames:
  tld: hololinked.net
  auth: auth.hololinked.net

cert:
  environment: dev
  enabled: true

routes:
  - name: frontend
    tls: true
    hostnameRef: tld
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /
        backendRefs:
          - name: frontend
            port: 80
  - name: backend
    tls: true
    hostnameRef: tld
    rules:
      - matches:
        - path:
            type: PathPrefix
            value: /api
        backendRefs:
          - name: backend
            port: 80
  - name: zitadel-iam
    tls: true
    hostnameRef: auth
    rules:
      - matches:
        - path:
            type: PathPrefix
            value: /
        backendRefs:
          - name: zitadel-iam
            port: 8080
  - name: zitadel-iam-login
    tls: true
    hostnameRef: auth
    rules:
      - matches:
        - path:
            type: PathPrefix
            value: /ui/v2/login
        backendRefs:
          - name: zitadel-iam-login
            port: 3000
  - name: http-upgrade-to-https-tld
    tls: false
    hostnameRef: tld
    rules:
      - filters:
          - type: RequestRedirect
            requestRedirect:
              scheme: https
              statusCode: 301
  - name: http-upgrade-to-https-auth
    tls: false
    hostnameRef: auth
    rules:
      - filters:
          - type: RequestRedirect
            requestRedirect:
              scheme: https
              statusCode: 301

