{{- if .Values.credentials.create }}
{{- $password := randAlphaNum 32 | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.name }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": pre-install,post-delete
type: Opaque
stringData:
  {{ .Values.credentials.dsnKey }}: "postgresql://{{ .Values.postgres.user }}:{{ $password }}@{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:5432/{{ .Values.postgres.database }}?sslmode=disable"
  postgres-user: {{ .Values.postgres.user | quote }}
  postgres-password: {{ $password | quote }}
  postgres-db: {{ .Values.postgres.database | quote }}
{{- end }}