{{- if .Values.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-{{ .Values.environment }}
spec:
  acme:
    server: {{ include "cert-issuer.acmeServer" . }}
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: {{ include "cert-issuer.fullname" . }}-key
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: {{ .Release.Namespace }}-namespace-gateway
                namespace: {{ .Release.Namespace }}
                kind: Gateway
{{- end }}