{{- if .Values.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  annotations:
    {{- if and .Values.cert.enabled .Values.cert.environment }}
    cert-manager.io/issuer: letsencrypt-{{ .Values.cert.environment | lower }}
    {{- end }}
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  gatewayClassName: kgateway-external-{{ $.Release.Namespace }}
  listeners:
  {{- range $hostnameKey, $hostname := .Values.hostnames }}
    - name: {{ printf "https-%s" ($hostname | replace "." "-") | trunc 63 | trimSuffix "-" }}
      hostname: {{ $hostname }}
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: {{ printf "%s-tls" ($hostname | replace "." "-") | trunc 63 | trimSuffix "-" }}
      allowedRoutes:
        namespaces:
          from: Same
    - name: {{ printf "http-%s" ($hostname | replace "." "-") | trunc 63 | trimSuffix "-" }}
      hostname: {{ $hostname }}
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
  {{- end }}
{{- end }}

